#ifndef INC_FjolnirCodegenTokenTypes_hpp_
#define INC_FjolnirCodegenTokenTypes_hpp_

ANTLR_BEGIN_NAMESPACE(ff)
/* $ANTLR 2.7.3-20030430: "FjolnirCodegen.g" -> "FjolnirCodegenTokenTypes.hpp"$ */

#ifndef CUSTOM_API
# define CUSTOM_API
#endif

struct CUSTOM_API FjolnirCodegenTokenTypes {
	enum {
		EOF_ = 1,
		EIN_SEMIKOMMA = 4,
		EIN_JAFNTOG = 5,
		EIN_MINNA = 6,
		EIN_SVIGIOPNA = 7,
		EIN_SVIGILOKA = 8,
		EIN_ITRUN = 9,
		EIN_INNFLUTT = 10,
		EIN_SAMSETNING = 11,
		EIN_HLIDSETNING = 12,
		EIN_ITRUDHLIDS = 13,
		EIN_OPNASLAUFU = 14,
		EIN_STRENGUR = 15,
		StyriStafur = 16,
		HexStafur = 17,
		NafnStafur = 18,
		EIN_NAFN = 19,
		WS = 20,
		COMMENT = 21,
		EndOfLine = 22,
		EIN_LOKASLAUFU = 23,
		ADGERD_7 = 24,
		ADGERD_6 = 25,
		ADGERD_5 = 26,
		ADGERD_4 = 27,
		ADGERD_3 = 28,
		ADGERD_2 = 29,
		ADGERD_1 = 30,
		L_ANNARS = 31,
		L_ANNARSEF = 32,
		L_BREYTA = 33,
		L_EDA = 34,
		L_EFLOK = 35,
		L_EF = 36,
		L_EKKI = 37,
		L_FYRIR = 38,
		L_INNFLUTT = 39,
		L_KOSTUR = 40,
		L_LYKKJA = 41,
		L_LYKKJULOK = 42,
		L_MEDAN = 43,
		L_OG = 44,
		L_SKILA = 45,
		L_STADVAER = 46,
		L_STEF = 47,
		L_STOFN = 48,
		L_STOFNLOK = 49,
		L_UR = 50,
		L_UT = 51,
		L_VAL = 52,
		L_VALLOK = 53,
		L_THA = 54,
		INNSETNING = 55,
		GILDISVEITING = 56,
		SVIGI_OPNA = 57,
		SVIGI_LOKA = 58,
		SEMIKOMMA = 59,
		KOMMA = 60,
		HORNKLOFI_OPNA = 61,
		HORNKLOFI_LOKA = 62,
		PUNKTUR = 63,
		PUNKTURPUNKTUR = 64,
		STAFFASTI = 65,
		STRENGFASTI = 66,
		INNSETN_GILDISV_ADGERD_EDA_TALA = 67,
		FJOLDATALA = 68,
		HEILTALA = 69,
		FLEYTITALA = 70,
		TOMAGILDI = 71,
		AdgerdaStafur = 72,
		EkkiAdgerdaStafur = 73,
		ADGERD = 74,
		EkkiNafnStafur = 75,
		NAFN = 76,
		SLAUFA_OPNA = 77,
		SLAUFA_LOKA = 78,
		NAFNARUNA = 79,
		SKILGREININGAR = 80,
		SEGDARUNA = 81,
		LYKKJUSKILYRDI = 82,
		EINUNDARADGERD = 83,
		LISTI = 84,
		FYLKISGILDISVEITING = 85,
		L_BOD = 86,
		L_HLUTUR = 87,
		L_ARFUR = 88,
		NULL_TREE_LOOKAHEAD = 3
	};
};
ANTLR_END_NAMESPACE
#endif /*INC_FjolnirCodegenTokenTypes_hpp_*/
